### ISSUE TITLE
Cannot access the Operator Hub with Basic Sample

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-base-ocp-vpc#484]
I deployed the sample `basic`
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/tree/main/examples/basic

but I cannot access the Operator Hub in the OpenShift console
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/0fbb63dc-df88-412b-b974-a16da272f358">

**Comment by imprateeksh** [comment]
Hi @lionelmace - This is happening due to the variable `disable_outbound_traffic_protection` taking the default value as `false`. If you want to have this, you can open up outbound traffic by setting this variable to true, for example as shown below:
![image](https://github.com/user-attachments/assets/f553dc49-d726-4161-8549-f24632683a91)
